### PR TITLE
Add config setup for hparam tuning

### LINKED ISSUE #41: Make config setup for hyperparameter tuning of deep model
We should use config files to manage hyperparameter tuning. Yaml is a pretty decent and readable format.
I'll be working on it as part of my mission to beat the bayes model.

### PR DESCRIPTION
**Pull request by marksverdhei**
This pull request includes an implementation of hyperparameter selection from config files. 
The configs are in yaml format, and should follow the pattern of `rnn_default.yaml`.
This pr also includes tensorboard metrics for the model 

Closes #41

### CODE REVIEW

**Comment by LBlend** [comment]
There's an error

```
File "/app/src/classifier.py", line 14, in <module>
	rnn_model = keras.models.load_model('bin/rnn')

ValueError: Unable to restore custom object of type _tf_keras_rnn_layer currently. Please make sure that the layer implements `get_config`and `from_config` when saving. In addition, please use the `custom_objects` arg when calling `load_model()`.
```

I've only tested using the current docker-compose configuration

**Comment by marksverdhei** [comment]
What version of tensorflow are you using in the docker container?

**Comment by LBlend** [comment]
> What version of tensorflow are you using in the docker container?

It's too long time ago for me to remember but basing of the date of the pull request comment I'm guessing 2.6.0 or 2.4.2

**Comment by marksverdhei** [comment]
I see. I've been trying to reproduce the error but i'm having trouble setting up a docker configuration on my computer. Looking at the error, it looks like the problem might be a TF version discrepency which is why I asked for the version, given that it works ~fine when building it manually. This is another motivation for #45

**Comment by LBlend** [comment]
Ok, I'm assuming that it's fine then and that it'll fix itself when rewriting the backend. Since I'm not gonna update the server instance before completing the rewrite I'm just gonna go ahead and merge the pulll request. It's no big deal whether or not the build breaks for now

**Comment by LBlend** [comment]
Does that sound good to you?

**Comment by marksverdhei** [comment]
Yep

**Comment by marksverdhei** [comment]
Or well, whether it will fix itself might depend on the TF version we end up using.
FYI i've been running TF Version: 2.4.1

**Comment by marksverdhei** [comment]
Just realized now that after running the `black` autoformatter, it replaced all single quotes with double quotes. Maybe this should be reverted. Oops

**Comment by LBlend** [comment]
No worries. We'll fix it later. I'm thinking of changing the requirements anyway so that black or some other formatter will do everything automatically for us

**Pull request merged**
